const CHANGE_TOP_BANNERS = "recommend/CHANGE_TOP_BANNERS";
const CHANGE_HOT_RECOMMEND="recommend/CHANGE_HOT_RECOMMEND";
const CHANGE_NEW_ALBUM="recommend/CHANGE_NEW_ALBUM";
const CHANGE_SOARING_LIST="recommend/CHANGE_SOARING_LIST";
const CHANGE_PUBLISHING_LIST="recommend/CHANGE_PUBLISHING_LIST";
const CHANGE_ORIGINAL_LIST="recommend/CHANGE_ORIGINAL_LIST";
const CHANGE_SETTLE_SINGERS="recommend/CHANGE_SETTLE_SINGERS"
const CHANGE_HOT_ANCHOR="recommend/CHANGE_HOT_ANCHOR"

export {CHANGE_TOP_BANNERS,CHANGE_HOT_RECOMMEND,CHANGE_NEW_ALBUM,CHANGE_SOARING_LIST,CHANGE_PUBLISHING_LIST,CHANGE_ORIGINAL_LIST,CHANGE_SETTLE_SINGERS,CHANGE_HOT_ANCHOR}