const TOP_LIST_INFO='ranking/TOP_LIST_INFO'
const TOP_LIST_DETAIL='ranking/TOP_LIST_DETAIL'
const CURRENT_TOP_LIST_ID='ranking/CURRENT_TOP_LIST_ID'
const TOP_LIST_CMT_COUNTS='ranking/TOP_LIST_CMT_COUNTS'
const TOP_LIST_CMT_CONTENTS='ranking/TOP_LIST_CMT_CONTENTS'
export {TOP_LIST_INFO,TOP_LIST_DETAIL,CURRENT_TOP_LIST_ID,TOP_LIST_CMT_COUNTS,TOP_LIST_CMT_CONTENTS};