const SONG_CATEGORY_LIST_COUNTS='songs/SONG_CATEGORY_LIST_COUNTS';
const SONG_CATEGORY_LIST='songs/SONG_CATEGORY_LIST';
const SONG_CATEGORIES='songs/SONG_CATEGORIES';
const CURRENT_CATEGORY='songs/CURRENT_CATEGORY';

export {SONG_CATEGORY_LIST_COUNTS,SONG_CATEGORY_LIST,SONG_CATEGORIES,CURRENT_CATEGORY}
