const CHANGE_SONG_DETAIL='bottom-player/CHANGE_SONG_DETAIL'
const CHANGE_SONG_URL='bottom-player/CHANGE_SONG_URL'
const CHANGE_SONG_LYRIC='bottom-player/CHANGE_SONG_LYRIC'
const CHANGE_PLAY_LIST='bottom-player/CHANGE_PLAY_LIST'
const CHANGE_CURRENT_SONG_INDEX='bottom-player/CHANGE_CURRENT_SONG_INDEX'
const CHANGE_SEQUENCE='bottom-player/CHANGE_SEQUENCE'
const CHANGE_CURRENT_LYRIC_INDEX='bottom-player/CHANGE_CURRENT_LYRIC_INDEX'

export {CHANGE_SONG_DETAIL,CHANGE_SONG_URL,CHANGE_SONG_LYRIC,CHANGE_PLAY_LIST,CHANGE_CURRENT_SONG_INDEX,CHANGE_SEQUENCE,CHANGE_CURRENT_LYRIC_INDEX};